### ISSUE TITLE
Game Crashes during some Multi-battles

### ISSUE THREAD

**Issue by mFireworks** [mFireworks/Triple-Battle-Converter#3]
As seen within mopo's video: https://www.youtube.com/watch?v=BBTpeAE98NA&t=1717s

When he reaches the team plasma's ship, there's some multi-battles on the ship that caused the game to crash. My guess to this issue is that these multi-battles were marked to be triple battles, so the game got confused when certain actions occurred.

Sadly, I can't find a mapping of these battles to trainer IDs. so a full playthrough of this game would be required. The list of multi-battles in the game can be found [here](https://bulbapedia.bulbagarden.net/wiki/Multi_Battle#In-game_events). Each of these trainers would need to be given a unique team of pokemon with the trainer editor, then encountered in-game to figure out which grunts are apart of the multi-battles. I'm sure there's better tools out there to figure this out, but I can't find them nor know how to achieve that through the tools I do have.

**Comment by SpecterSpectrum** [comment]
So will a save editor have to be used to skip this segment? He says in the video that he skipped it, but if I remember correctly, that's a mandatory story event, so it wouldn't be skippable with modding the game somehow.

**Comment by mFireworks** [comment]
> So will a save editor have to be used to skip this segment? He says in the video that he skipped it, but if I remember correctly, that's a mandatory story event, so it wouldn't be skippable with modding the game somehow.

Watching back his vod, it looks like he just kept trying the fight till he makes it through. It seems like there's merely a *chance* to freeze at the start of each turn. Doesn't seem consistent on the exact trigger. So you can make it through the fights, might just take a couple tries to complete it without it freezing up. Still worth to track down these fights and edit them to prevent this issue from happening.

Update: So, turns out I still have the rom I made for him, so matching up his fights with the data in the rom I was able to find most of the multi-battle ids. I'm just missing one fight and asked the don if he still has the footage of that fight. Worst comes to worst, I'd only have to play up to Driftveil City, which is much more manageable than the end of the game.

**Comment by mFireworks** [comment]
Commit e373462 should resolve this issue, was able to track down the last of the trainer IDs. Won't build a new executable just yet, going to wait to resolve #4 before releasing a new version.
