### ISSUE TITLE
Wild Encounters Freeze Game

### ISSUE THREAD

**Issue by Ram0-12** [mFireworks/Triple-Battle-Converter#5]
Hey sorry never used GitHub for this before but just had an issue when testing.
First of all nice work on the hack! I’ve seen it and thought this looks like a really fun game to play so I decided I wanted to play White 2
But I’ve followed all the steps for the guide and on your YouTube video for Pokémon White 2 and I’ve ran into a problem that when a wild battle is about to start (grass, cave and even the catch tutorial) the game freezes before entering the battle. 
Now I still got to walk through walls and see if trainer battles work correctly but atm not being able to encounter wild Pokémon is pretty crucial for a Nuzlocke. As well as that I was going to try and just do Pokémon White 1 instead and see if that would work.
Sorry for the long message.

**Comment by mFireworks** [comment]
Thanks for trying it out!

When you did the randomization with PokeRando-ZX, did you turn on the **Fix Music** option under **Starters, Statics & Trades**? Turning that option on in the gen 5 games causes wild encounters to freeze, it's a known issue with the randomizer. Others have reported similar issues (see #4) and that was the cause.

**Comment by Ram0-12** [comment]
Ohh I didn't even think about that! Yes I did have it ticked. I tried so many other settings for the randomiser that could have been an issue. Cheers!
