### ISSUE TITLE
Error with Triple Battle converter and Gen VI games

### ISSUE THREAD

**Issue by DeathwingGamer** [mFireworks/Triple-Battle-Converter#6]
Posted about this in the discord and here is a shortened version:

Was trying to use the triple battle converter with pokemon X and when I tried to convert all the trainers into triple battles it gave me an error saying the given file size of my trdata folder didn't match what was expected for Black and White even though I was converting X and Y. 

[trdata.zip](https://github.com/user-attachments/files/16506062/trdata.zip)
Here is my trdata folder as requested

**Comment by mFireworks** [comment]
Looking into it, I think the files within your trdata got corrupted. Trying to take your file and inserting it into my Pokemon X crashes pk3DS, so something is unexpected within it. From what I can find, your `000.bin` file is 4 bytes longer than expected. How it got into this state, I'm not sure.

Now, I'm not sure if that trainer is used at all, looking at it in the trainer editor doesn't seem to bring up valid data. You might be able to replace it with this `000.bin`, which is yours with the last 4 bytes removed. The converter worked for me with the modified file, but not sure if it'll have any affect in-game. Give it a try for now, and I'll work on adjusting the program to get around this problem better.
[000.zip](https://github.com/user-attachments/files/16517996/000.zip)

**Comment by mFireworks** [comment]
This should be fixed with change d57f03f, just will now skip `000.bin` when calculating out the file size. We don't even modify that file, so if its size is unreliable, we shouldn't use it in our protection checks.

Probably will release a hotfix for this, just in case others run into this issue.
